name: "ESP-IDF Project Upload"
description: "Upload ESP-IDF project"
inputs:
  PROJECT_PATH:
    description: "Path for the project to upload"
    required: true
  ARTIFACT_NAME:
    description: "Artifact name to upload"
    required: true
runs:
  using: "composite"
  steps:
      - name: esp32 upload project
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: |
            ${{ inputs.PROJECT_PATH }}/build/bootloader/*.bin
            ${{ inputs.PROJECT_PATH }}/build/partition_table/*.bin
            ${{ inputs.PROJECT_PATH }}/build/*.bin
            ${{ inputs.PROJECT_PATH }}/build/flash_project_args
            ${{ inputs.PROJECT_PATH }}/build/config/sdkconfig.json
